### ISSUE TITLE
MSVC - multi-threaded debug (/MTd) version of static lib

### ISSUE THREAD

**Issue by hasaranga** [magiblot/tvision#110]
Can you also provide multi-threaded debug (/MTd) version of static lib for MSVC? Artifacts section contains only the release version.

**Comment by magiblot** [comment]
Yes, of course. Besides the /MTd flag, do you also need the library to be built with debug info?

**Comment by magiblot** [comment]
In the libraries artifact of the [last workflow](https://github.com/magiblot/tvision/actions/runs/6371517084) you will now find these new files:
```
RelWithDebInfo/tvision-relwithdebinfo.lib
RelWithDebInfo/tvision-relwithdebinfo.pdb
```
What you are looking for is `tvision-relwithdebinfo.lib`. This file is built with `/MTd`. You can ignore the pdb file.

Let me know if that worked.

**Comment by hasaranga** [comment]
I think I needed debug with debug info. Not release with debug info.

**Comment by magiblot** [comment]
Okay, I have added `tvision-debug.lib`. See now if it works.

Also, make sure you are using the last version of the header files. They may have been ABI-breaking changes since the last time you downloaded them.

**Comment by hasaranga** [comment]
That works great!
So easy to work with Visual Studio.  I just added **include** dir into the project **includes**. And linked with lib file. Then added **/permissive- /Zc:__cplusplus** compiler command line.
