### ISSUE TITLE
Build failure on OpenBSD

### ISSUE THREAD

**Issue by notepade** [magiblot/tvision#13]
I wanted to test if this program worked on OpenBSD (and NetBSD too, but that is for later) and I got this error. I didn't have any issues with cmake, but both make and gmake failed on me.

make:
![make](https://user-images.githubusercontent.com/71466591/94341542-24953b00-ffd8-11ea-8739-3fdce711fa93.png)

gmake:
![gmake](https://user-images.githubusercontent.com/71466591/94341549-2bbc4900-ffd8-11ea-9c13-8470c02d9fda.png)

What is the issue at hand? Can this please be fixed?

**Comment by magiblot** [comment]
Hi notepade!

For the time being, just change line 57 in `source/platform/sighandl.cpp` from this:
```c++
if (c == 'c' || c == '\n')
    context->uc_mcontext.IP++; // Increase instruction pointer.
```
To this:
```c++
if (c == 'c' || c == '\n')
    ;
```

**Comment by magiblot** [comment]
And line 83 from this:
```c++
"\r\n", (void*) context->uc_mcontext.IP);
```
To this:
```c++
"\r\n", (void*) 0);
```

**Comment by magiblot** [comment]
This issue is caused by a non-portable feature which I thought would be cool but actually has no real world use. It fails to compile every time someone tries to build Turbo Vision in a different BSD system. I think it will be best to remove it.

**Comment by notepade** [comment]
Okay. It worked making with the changes. A bunch of warnings, but that can be ignored for now. I tried to compile the hello example to see how it looked, but using -std=c++17 gave a strange error that it didn't recognize it.
![C++](https://user-images.githubusercontent.com/71466591/94341793-54ddd900-ffda-11ea-95a0-6a13da15a38a.png)

And then another error when removing it.
![error1](https://user-images.githubusercontent.com/71466591/94341797-5c9d7d80-ffda-11ea-944c-8e7462c80114.png)

Any further changes you recommend I make?

**Comment by magiblot** [comment]
If cmake and make already work, then you do not need to compile hello manually. You should be able to find the demo applications (`tvdemo`, `tvedit`, etc.) already built in the same directory.

If you still want to build `hello.cpp` manually: the errors you got are not normal. Maybe try with `clang++` instead of `g++`?

**Comment by notepade** [comment]
hello.cpp worked with clang++. It didn't like g++ for some reason. Gave a few warnings, but again, that can be ignored for now. It would be best to remove the non portable features if they have no real purpose. That way it can work on other BSD systems without issue.
