### ISSUE TITLE
Cannot compile under BCPP 5.02 with TASM 5.0 (Win 98 SE)

### ISSUE THREAD

**Issue by Maxwelldoug** [magiblot/tvision#21]
Trying to compile geninc gives several errors related to missing files (which are in fact missing from source) and geninc32 simply states "Invalid target->/Ts" I'm banging my head against the wall here as my co-worker on this project, Sduensin, tells me he's managed to compile it fine in his build environment under windows 3.1 I've followed the instructions in build.txt until now, can anyone tell me what I'm doing wrong here?

**Comment by magiblot** [comment]
Hi Doug!

Are you building from the IDE? I suggest you try the makefile instead. It will save you a lot of time; in fact I should just remove the IDE project since I no longer update it. Sorry for the confusion.

As the Readme says, the commands to build with the makefile are:

```sh
cd project
make.exe <options>
```

Where common options are `-DDOS32`, `-DDEBUG`, `-DTVDEBUG`, etc. See https://github.com/magiblot/tvision#windowsdos-borland-c for more details.

The commands above work out-of-the-box for me, using BCPP 4.52 and TASM 4.0. Can you please try if it works for you?

Cheers.

**Comment by Maxwelldoug** [comment]
ah, that might explain a bit. I'll try that, thanks.

**Comment by Maxwelldoug** [comment]
Nope. Still not compiling. and now I can't read the errors because you can't scroll up in the DOS Prompt.

**Comment by magiblot** [comment]
Can you try redirecting MAKE's output with `>` or `2>`?

**Comment by Maxwelldoug** [comment]
I have, to output.log, but github does not work on IE 6.

**Comment by magiblot** [comment]
Then I recommend you to create a Windows XP virtual machine and build from there. It's well supported by VirtualBox/VMWare, so you can have dynamic resolutions, shared folders, etc. It's going to save you a lot of time.

In the meantime, does IE 6 support pastebin?

**Comment by Maxwelldoug** [comment]
No it does not. I've mounted the VHD in windows's partition manager, here's the log.
[output.log](https://github.com/magiblot/tvision/files/5409953/output.log)

**Comment by magiblot** [comment]
Oh, this doesn't look good. It fails to run the command `GENINC.EXE > TVWRITE.INC`, but I can't see any error message. Can you check the contents of `TVWRITE.INC`?

**Comment by magiblot** [comment]
`TVWRITE.INC` gets deleted by make, so you may have to run that command manually.

**Comment by Maxwelldoug** [comment]
GENINC.EXE is not present, compiler deleted it too.

**Comment by Maxwelldoug** [comment]
Or it didn't compile in the first place.

**Comment by magiblot** [comment]
How strange. Anyway, all this hardship is not normal. Consider downgrading to BC++ 4.52, which works for both me and Scott (you will have to install the DOS PowerPack again).

**Comment by Maxwelldoug** [comment]
DOS Power-whatnow?

**Comment by magiblot** [comment]
The Borland PowerPack for DOS. It's a compiler extension that adds support for DPMI and DPMI32 builds. I'm not sure you also need it for regular DOS builds, but both me and Scott have it installed.

But still, I recommend you to migrate to Windows XP for development.

See you!

**Comment by Maxwelldoug** [comment]
I had hoped to avoid that step given all the caveats that would bring about. (IE, not being able to transition to 86box for software testing without extra steps) but it's looking inevitable. thanks for the help.

**Comment by magiblot** [comment]
I updated the [build instructions](https://github.com/magiblot/tvision#build-borland) for Borland C++.

**Comment by Maxwelldoug** [comment]
Closing this as I've opened a new issue with a different problem later in the compiling.
