### ISSUE TITLE
Problem User #2 again, this time compiling fails under XP with BCPP 5.0 and TASM 5.0

### ISSUE THREAD

**Issue by Maxwelldoug** [magiblot/tvision#23]
[log2.txt](https://github.com/magiblot/tvision/files/5415816/log2.txt)
I've attached the log from the get-go this time. thank you for recommending XP, I finally have guest additions.

**Comment by magiblot** [comment]
> NOTE: Exited with message stating that TASM doesn't exist, but it is definitely installed.

If it is installed, then make sure that:

* It is also available in `PATH` (if not, you will have to add TASM's `BIN` directory to this environment variable).
* You have both the 16-bit and 32-bit versions of TASM (i.e. `tasm` and `tasm32`).

**Comment by Maxwelldoug** [comment]
thanks, somehow missed that step. trying again now.

**Comment by Maxwelldoug** [comment]
Nope, same issue, 100% in PATH.

**Comment by Maxwelldoug** [comment]
TASM, TASM32, TASMX all present in the relevant folder.

**Comment by magiblot** [comment]
But can you call them from the command line?

**Comment by Maxwelldoug** [comment]
oh for- no it isn't. I'm not crazy, it's definitely in path.

**Comment by magiblot** [comment]
Maybe you need to open a new console? Or there is a spelling mistake in PATH?

**Comment by Maxwelldoug** [comment]
nope, literally copy/pasted the directory in the same format as BCPP then restarted the VM. BCCP's excecutables work fine. That is *very* odd.

**Comment by magiblot** [comment]
How do you set the PATH variable?

**Comment by Maxwelldoug** [comment]
control panel- System- advanced- Environment Variables- select path- edit- add the directory followed by a semicolon, save, exit, reboot

**Comment by magiblot** [comment]
Yes, that's the intended way to it. So what do you see if you run `echo %PATH%` in the command line? Does it match what you set in the control panel?

**Comment by Maxwelldoug** [comment]
that's an affirmative. however, for some reason, there's a space where there shouldn't be, which I didn't add and would explain the issue. let's try this again.

**Comment by magiblot** [comment]
It could also be a non-printable character. These things happen often.

**Comment by Maxwelldoug** [comment]
awesome, TV.lib generated, but there are still feckin errors, FFS.

**Comment by Maxwelldoug** [comment]
geninc32 still not present as well.

**Comment by magiblot** [comment]
Can you please generate the logs this way?
```
make > out.txt 2> err.txt
```

**Comment by Maxwelldoug** [comment]
[out.txt](https://github.com/magiblot/tvision/files/5416185/out.txt)

err.txt is empty and git won't take it.

**Comment by magiblot** [comment]
```
Error calendar.cpp 140: Illegal structure operation in function TCalendarView::draw()
Error calendar.cpp 160: Illegal structure operation in function TCalendarView::draw()
```
This is a compilation error. It's rejecting the following lines in `examples/tvdemo/calendar.cpp`:
```c++
    ostrstream( str, sizeof str)
      << setw(9) << monthNames[month] << " " << setw(4) << year // <-- this one
      << " " << (char) 30 << "  " << (char) 31 << " " << ends;
```
```c++
                ostrstream( str, sizeof str )
                  << setw(2) << (int) current << ends; // <-- and this one
```

I have no idea why it fails, but I guess you can just comment them out.

**Comment by Maxwelldoug** [comment]
that second thing you mentioned isn't even in the file.

**Comment by Maxwelldoug** [comment]
nope, ignore that, just ctrl+f being bad

**Comment by Maxwelldoug** [comment]
[out2.txt](https://github.com/magiblot/tvision/files/5416250/out2.txt)
err empty once again, still error'd.

**Comment by magiblot** [comment]
```
Error calendar.cpp 161: Statement missing ; in function TCalendarView::draw()
Error calendar.cpp 163: Misplaced else in function TCalendarView::draw()
```

Are you familiar with C++?

**Comment by magiblot** [comment]
On line 160 you cannot just comment out the whole line. You need to leave a semicolon at the end of the statement.

**Comment by Maxwelldoug** [comment]
depends what you mean. I do quite a bit of work in C++, but I build code for nintendo consoles with entirely different instructions sets.

https://github.com/devkitPro/nds-examples/blob/master/hello_world/source/main.cpp this is what helloworld looks like on the DS.

**Comment by Maxwelldoug** [comment]
I'm better at stringing code snippets from stackexchange articles together then writing my own TBH.

**Comment by magiblot** [comment]
Also, is there a specific reason why you are using Borland C++ 5.02 instead of 4.52?

**Comment by Maxwelldoug** [comment]
mainly because it's a newer piece of software and the one my father owns a copy of :P

**Comment by magiblot** [comment]
I think I know why it fails. Can you try with the following changes?

Near line 140:
```diff
-    ostrstream( str, sizeof str)
-      << setw(9) << monthNames[month] << " " << setw(4) << year
-      << " " << (char) 30 << "  " << (char) 31 << " " << ends;
+        {
+        ostrstream( str, sizeof str) os;
+        os << setw(9) << monthNames[month] << " " << setw(4) << year
+           << " " << (char) 30 << "  " << (char) 31 << " " << ends;
+        }
```
Near line 160:
```diff
-                ostrstream( str, sizeof str )
-                  << setw(2) << (int) current << ends;
+                    {
+                    ostrstream( str, sizeof str ) os;
+                    os << setw(2) << (int) current << ends;
+                    }

```

**Comment by Maxwelldoug** [comment]
Alright, that seems good... no error messages anywhere in the log. thanks for the help! I'll request my friend's sample code and get back to you if anything else breaks.
