### ISSUE TITLE
Right-to-left (RTL) text support needs improvement, including fixing the README

### ISSUE THREAD

**Issue by eplodn** [magiblot/tvision#35]
From the `README`:
```
        *new TMenuItem( "העברית ~א~ינטרנט", cmNo, kbNoKey, hcNoContext ) +
         newLine() +
```
This should create the text `העברית אינטרנט` with the `א` (at the beginning of the leftmost word) in red.

Instead, as can be seen on the screenshot, it creates a different text `ינטרנטא העברית` where the words have now switched sides, and the `א` has moved from the beginning of the word (right) to its end (left). This way the word `אינטרנט` ("internet") has become `ינטרנטא` ("yanterneta"?).

**Comment by magiblot** [comment]
Hey Efi, thanks for the report.

Turbo Vision does not process RTL text any differently than the rest. It is the terminal emulator which takes care of displaying it properly.

I went and tried the same text in different terminal emulators:

![Screenshot_20201214_135724](https://user-images.githubusercontent.com/20713561/102083754-59b16c80-3e14-11eb-8c1f-b0360f97cd8a.png)

From left to right:

1 - `konsole` (same as in README): seemingly buggy RTL support. Seems to get confused by `א` being in a different color.
2 - `kitty`: similar to `konsole`, but it colors a different character.
3 - `gnome-terminal`: this looks fine, right?
4 - `alacritty`: no RTL support.
5 - `xterm`: no RTL support.

I guess I should submit a bug report to the applications exhibiting unexpected behaviour.

**Comment by eplodn** [comment]
Thanks for quick response! The third one indeed looks fine. What about Windows terminal?

May I suggest you render the multi-language example in that terminal for the `README` and proceed to close the issue.

**Comment by magiblot** [comment]
> May I suggest you render the multi-language example in that terminal for the README and proceed to close the issue.

Yes, this is the shortest way round.

> What about Windows terminal?

I have no idea, I'll have to try later.

**Comment by magiblot** [comment]
Konsole bug report: https://bugs.kde.org/show_bug.cgi?id=403729
