### ISSUE TITLE
tvhc: use stderr

### ISSUE THREAD

**Issue by electroly** [magiblot/tvision#41]
This is a pretty minor issue, but it would be nice if tvhc used `cerr` to print warnings/errors and `cout` for the copyright notice. Currently it uses `cout` for everything, so there's no easy way to silence the copyright notice without also silencing errors.

**Comment by magiblot** [comment]
Okay. This also matches the behaviour fo `gcc` or `clang`: standard output for things like `--help` and standard error for compiler diagnostics.

Can you check whether https://github.com/magiblot/tvision/commit/40e616d968c872745f22c217da87a779dc8738f2 works well enough for you? The only messages printed with `cout` are now the copyright and the usage information. Note that the "Overwrite?" messages were already using `cerr` and I haven't changed that.

Cheers.

**Comment by electroly** [comment]
That's perfect. Thank you!
