### ISSUE TITLE
Cannot compile tvision in win32

### ISSUE THREAD

**Issue by bugbit** [magiblot/tvision#47]
Error en tvision/source/platform/winwidth.cpp

 error C2061: error de sintaxis: identificador 'TStringView'

solution:

in tvision/source/platform/winwidth.h:

add #include <tvision/tv.h> for resolver bug :  error C2061: error de sintaxis: identificador 'TStringView'

the code would look like this:

#ifndef WINWIDTH_H
#define WINWIDTH_H

#ifdef _WIN32

// add #include <tvision/tv.h> for resolver bug :  error C2061: error de sintaxis: identificador 'TStringView'
#include <tvision/tv.h>
#include <tvision/compat/win.h>
#include <cstddef>
#include <cstdint>
#include <vector>
#include <mutex>
#include <unordered_map>

......

**Comment by magiblot** [comment]
Gracias. Me ha pasado por alto porque los PCH ya incluyen `tv.h`. Seguramente tu versión de CMake es más antigua y no soporta PCH, y has topado con el error.

¡Saludos!
