### ISSUE TITLE
Wrong whitelist rule causes `rg` to fail to search code content

### ISSUE THREAD

**Issue by flw-cn** [magiblot/tvision#49]
See also BurntSushi/ripgrep#1819, I can't search code via `rg`, because rg will search the contents of the repository as directed by the `.gitignore` rules, not by the files actually owned by the repository.

```
❯ rg TApplication::TApplication
(nothing)

❯ rg --no-ignore TApplication::TApplication
source/tvision/tapplica.cpp
41:TApplication::TApplication() :
```

I think this may cause some difficulties for me to read the source code. Hopefully it will improve.

**Comment by magiblot** [comment]
Yeah, the `.gitignore` rules are abusive. I wasn't aware this would affect the behaviour of third-party tools. Thanks for having the patience to report both in ripgrep and here.

The main reason why I never considered switching to a `grep` alternative (and thus I didn't reproduce this myself) is that `grep -rnI` has worked well enough for me. Am I missing any interesting features `ripgrep` has?
