### ISSUE TITLE
Turbo Vision Screenshots Thread

### ISSUE THREAD

**Issue by magiblot** [magiblot/tvision#7]

**Comment by magiblot** [comment]
An early stage of [turbo-mle](https://github.com/magiblot/turbo-mle).
![Screenshot_20200713_020355](https://user-images.githubusercontent.com/20713561/87260590-fe6cfe00-c4b2-11ea-91ce-622f32dd2faa.png)

**Comment by magiblot** [comment]
A showcase of Turbo Vision's Unicode display capabilities.
![Screenshot_20200804_174221](https://user-images.githubusercontent.com/20713561/89314567-18e16400-d67a-11ea-950f-d4c35d40e5f7.png)

**Comment by magiblot** [comment]
The [Turbo text editor](https://github.com/magiblot/turbo).

![Screenshot_20200806_174139](https://user-images.githubusercontent.com/20713561/89552632-b7053380-d80c-11ea-92e0-a8c30f80cd49.png)

**Comment by magiblot** [comment]
A context menu (`TMenuPopup`) in `TEditor`.
![Screenshot_20200829_045346](https://user-images.githubusercontent.com/20713561/91626951-cb73c080-e9b3-11ea-9206-e54e798740b6.png)

**Comment by magiblot** [comment]
Borland C++ vs MSVC builds on Windows 7 (see the differences in the filename encodings).
![tvision](https://user-images.githubusercontent.com/20713561/91917111-4e03c500-ecbf-11ea-92ff-0284fedb0bf1.png)

Bitmap font vs Lucida Console on Windows Vista.
![Anotación 2020-09-01 221605](https://user-images.githubusercontent.com/20713561/91917174-7a1f4600-ecbf-11ea-8c7a-2ec80d31d2ca.png)

**Comment by magiblot** [comment]
`tvdemo` on Windows 10, Unicode version (hence the CP437 characters instead of my system's default IBM850). Font is Consolas 18 pt.

![Turbo Vision Unicode Windows 10](https://user-images.githubusercontent.com/20713561/91992554-901b1e00-ed34-11ea-9b49-46d73bf4fb73.png)

**Comment by magiblot** [comment]
The Z80 IDE (`zide`) of ZXEmu2, a ZX-Spectrum emulator (http://zxemu2.sourceforge.net/). 

![Screenshot_20200913_214400](https://user-images.githubusercontent.com/20713561/93027120-1e33b600-f60b-11ea-9e7c-af8e2ffa4315.png)

**Comment by magiblot** [comment]
`tvdemo` running on [*That Terminal*](https://github.com/bisqwit/that_terminal) with the 8x19 font.

![Screenshot_20200914_010415](https://user-images.githubusercontent.com/20713561/93030841-7330f580-f626-11ea-83b2-455d1d5884dd.png)

**Comment by magiblot** [comment]
`tvdemo`'s color picker on Xterm, with the default palette in the right and with the VGA palette in the left.

![Screenshot_20200924_204018](https://user-images.githubusercontent.com/20713561/94193219-5e6b2200-feb0-11ea-8f54-2bb691c32420.png)

**Comment by magiblot** [comment]
The [Turbo text editor](https://github.com/magiblot/turbo) on WSL2.

![Anotación 2020-10-16 105341](https://user-images.githubusercontent.com/20713561/96237869-16ff1f80-0f9e-11eb-8531-8d639e136c48.png)

**Comment by j-greig** [comment]
experimenting with custom backgrounds [macos]

<img width="2672" height="1527" alt="Image" src="https://github.com/user-attachments/assets/ec7350b1-4146-40c3-aacf-88fedcb59d6f" />

**Comment by pepinisillo** [comment]
Writing environment with Sixel/Kitty image support.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/3e09c468-09eb-4e3b-8cc7-3a9b32473683" />

**Comment by magiblot** [comment]
[battleships](https://github.com/Ddimk/battleships) (2021) by [Ddimk](https://github.com/Ddimk):

<img width="1080" height="570" alt="Image" src="https://github.com/user-attachments/assets/d1a94857-cb31-4752-a00e-cf549f302029" />

<img width="1080" height="570" alt="Image" src="https://github.com/user-attachments/assets/cbdfce9f-c6b8-4002-9a6a-7f3e081a6ced" />
