### ISSUE TITLE
add OSC52 "set clipboard" support to tvision internal text file editor control

### ISSUE THREAD

**Issue by unxed** [magiblot/tvision#82]
just like here: https://github.com/unxed/turbo/commit/59f54e3452fa462e65b1f4260efd36d0a1a1bbd0

**Comment by magiblot** [comment]
I have an idea on how to integrate clipboard support into the Turbo Vision API, but it's not going to be ready anytime soon.

**Comment by unxed** [comment]
Please keep in mind that clipboard support via far2l extensions would also be nice to do on the turbo vision side, so that all interactions with the terminal are in one place, and not distributed between turbo vision and turbo. Some details [here](https://github.com/magiblot/turbo/issues/2#issuecomment-1338234201).

**Comment by unxed** [comment]
Fantastic! Thanks a lot!
