### ISSUE TITLE
Is it possible to port it to UEFI shell?

### ISSUE THREAD

**Issue by ziv2013** [magiblot/tvision#91]
Hi,

I have used Turbo Pascal for many years. And I work as a BIOS engineer these days. I'm wondering if possible to port Turbo vision to UEFI shell?

Ziv

**Comment by magiblot** [comment]
Hi!

Good question. Turbo Vision can work even on MS-DOS, so I don't see why it couldn't support the UEFI environment. However, I have no idea how to do it.

**Comment by ziv2013** [comment]
Hi,

Thanks for your reply. I would study this.

Ziv
