### ISSUE TITLE
How to download the binaries?

### ISSUE THREAD

**Issue by GHExplorer** [magiblot/tvision#94]
Hi,

I'm trying to download the binaries for MinGW/Windows.  But I don't underserstand how to get there.

Starting with this:

https://github.com/magiblot/tvision/actions/runs/4038584786

, then selecting Windows (MinGW), https://github.com/magiblot/tvision/actions/runs/4038584786/jobs/6942679993

leads to the page below.  I don't see a link to an executable or zip file containing the binaries.

Obviously, I'm misunderstanding something.

![image](https://user-images.githubusercontent.com/4349455/216832472-afdb1a31-ee5a-4b64-b5e9-cbbecb50f0d8.png)

**Comment by magiblot** [comment]
Hi @GHExplorer!

No, the executables are not there. They are at the bottom of https://github.com/magiblot/tvision/actions/runs/4038584786, where it says "Artifacts". I think you must be logged in before you can see this section. What you are looking for are the `examples-x64` or `examples-x86` artifacts.

Sorry for the confusion!

The

**Comment by GHExplorer** [comment]
Got it, thanks magiblot.
