### ISSUE TITLE
use another tools instead of xclip on some operating systems

### ISSUE THREAD

**Issue by unxed** [magiblot/tvision#98]
` pbcopy` and `pbpaste` should be used under MacOS.

Also there are separate tools for WSL and Cygwin environments. Full list here:
https://gist.github.com/RichardBronosky/56d8f614fab2bacdd8b048fb58d0c0c7#file-cb

For Wayland:
```
    cat | wl-copy
    wl-paste
```

**Comment by magiblot** [comment]
Hi @unxed!

`pbcopy`/`pbpaste` are already being used on MacOS and `wl-copy`/`wl-paste` (part of the `wl-clipboard` package) are already being used in Wayland sessions ([unixcon.cpp](https://github.com/magiblot/tvision/blob/bb98e5f3b84239e114bdfd7313ee59ab31acb201/source/platform/unixcon.cpp#L31)).

Cygwin is not supported, so the only case that's missing is WSL. Thanks for the suggestion.

**Comment by unxed** [comment]
Probably full paths in WSL are not required, try
```
    cat | clip
    powershell Get-Clipboard | sed 's/\r//'
```
first

**Comment by magiblot** [comment]
In WSL, PowerShell was so slow and required so many workarounds that I switched to CScript. Pasting still takes a short delay but it is now a lot better.
